services:
  api:
    build: .
    ports:
      - "5000:5000"

  sql:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    expose:
      - '3306:3306'
      